import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('D:\\Python\\train.csv')
print(df.head())
print(df.tail())
print(df.info())
print(df.columns)
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.describe())
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
order_mean = df.groupby('Order ID')['Sales'].mean()
region_sales = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
category_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
subcategory_median = df.groupby('Sub-Category')['Sales'].median()
print(order_mean)
print(region_sales)
print(category_sales)
print(df['Row ID'].max())
print(df['Row ID'].min())
print(df.groupby('Category')['Row ID'].count())
print(subcategory_median)
top_region = region_sales.idxmax()
top_category = category_sales.idxmax()
print(top_region)
print(top_category)
#Plot 1: Sales by Region
region_sales.plot(kind='bar')
df.groupby('Region')['Sales'].sum().plot(kind='bar')
plt.title("Total Sales by Region")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()
#Plot 2: Sales by Category
category_sales.plot(kind='bar')
plt.title("Total Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()
#Plot 3: Sales by Distribution
df['Sales'].plot(kind='hist', bins=20)
plt.title("Sales Distribution")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()
